---
title: "General Information"
---

The Ministry of the Solicitor General annually releases data on the segregation, restrictive confinement, and deaths in custody of inmates in Ontario’s adult correctional system.

-   **Data Source**: Offender Tracking Information System (OTIS)
-   **Geographic coverage**: Ontario
-   **Update frequency**: Yearly
-   **Maintainer**: Ministry of the Solicitor General
-   **Maintainer Branch**: Business Intelligence and Insights Branch
-   **Publishing Branch**: Service Management and Oversight Branch
-   **Related Links**: [Data release of inmates in Ontario](https://www.ontario.ca/page/jahn-settlement-data-inmates-ontario)
-   **Last Validated Date**: November 3, 2025


### Important Notes

-   To simplify the provision of data, several data tables include information on both individuals in segregation conditions and individuals in restrictive confinement. Due to the differences in the way that the data on segregation conditions and restrictive confinement have been collected, and the differences in the definitions of these concepts, these numbers should not be compared to each other.
-   Some individuals may have both placements in restrictive confinement and segregation conditions, within the reporting period. Therefore, these numbers should not be added together when calculating proportions out of the total.
-    Resources on this page may be updated periodically. For information on data updates, please consult the available metadata such as data dictionary and supporting documentation.

### Key Definitions

**Segregation**: Defined in Ontario Regulation 778 as any type of custody where an inmate is in highly restricted conditions for 22 to 24 hours or does not receive a minimum of two hours of meaningful social interaction each day, excluding circumstances of an unscheduled lockdown. A record is created each time an inmate meets the conditions of segregation and closed when the inmate no longer meets those conditions. A break in a segregation placement is defined as occurring when an individual is out of segregation conditions for 24 or more continuous hours.

**Restrictive Confinement**: The Ministry of the Solicitor General defines restrictive confinement as any type of confinement that is more restrictive than the general population but less restrictive than segregation. As a result, the ministry is reporting on any case within the fiscal year reporting period where an individual was held in a unit regularly scheduled to be locked down for 17 hours or more per day. This timeframe is considered more restrictive than that of the general population based on an assessment of provincewide lockdown times. Regularly scheduled lockdowns are daily routine times where movement out of a cell is restricted, such as during meal times and overnight.